### PR TITLE
LPP-54642 If the configuration of index all article versions is disab…

### PR DESCRIPTION
**Pull request by Mikellorza**
This is a workaround about improve the performance when we are indexing versions of contents. When we have the configuration disable about index all versions we don't need to index some versions. About this, I've observed two use cases:

1. When we have some versions and we expire the last version, so we need to index the previous one version. I observed that with this change it is working fine, but it would be fine a double check.
2. When we have  also the configuration "Version History by Default Enabled"=disabled and "Journal Article Maximum Version Count"= 1, so in this case we are expiring the previous version when we are adding a new one, so in this case, with this development we don't call to index versions with higher version than the version that we are indexing, so, we are not re-indexing the version recently created in the expiration. This development also allow to delete previous versions from the index when we have the "index all versions" configuration disabled. Furthermore, If we use the condition if we have disable "Version History by Default Enabled" configuration instead of the version condition we will never delete from the index previous versions.

### CODE REVIEW

**Comment by Mikellorza** [comment]
ci:content:manegement

**Comment by Mikellorza** [comment]
ci:test:sf

**Comment by Mikellorza** [comment]
ci:help

**Comment by Mikellorza** [comment]
ci:test:content-management

**Comment by jkappler** [comment]
ci:report:31563208

**Comment by Mikellorza** [comment]
@jkappler It seems there is no related issues as I have seen in the report but as we commented many times this type of changes
 are very risky, so, I don't know what we can do. It is true that this only affects when we have index all versions disabled, so this shortens the uses cases but I still think that there is a high probability to broke some use cases in order to gain some performance, even I don't know if with this change we are going to gain a lot of optimization that is worth the risk.

**Comment by Mikellorza** [comment]
ci:close

**Pull request closed without merging**
